### PR TITLE
Release 2.3.3

### PR DESCRIPTION
**Pull request by denniskwon**

### CODE REVIEW

**Comment by haszari** [comment]
I did some general testing with syncing product variations ( #1794 ? ) - namely a t-shirt product in different sizes.

I didn't test all PRs/changes in this release. I'm happy to do more testing - if someone comments with testing instructions or areas to smoke test I can do another pass (cc @denniskwon @maxdupenois @budzanowski).

Here's what I found:

### Improved syncing of variable products (aka product variants) 🟢 
As far as I can tell, with 2.3.3, variable product syncing is improved - note the `Large` `Medium` in `Variants` column. In my testing with 2.3.2, this column was blank. 

2.3.3 - large/medium looking 👌 

Screen Shot 2021-03-19 at 2 36 53 PM

2.3.2 - variants are indistinguishable 😕 

Screen Shot 2021-03-19 at 2 17 47 PM 2

### Auto-sync all products on plugin upgrade ❌ 
I couldn't confirm this is happening. I was testing with a release build (`npx sake zip`) of the plugin on a [test site](https://handicapped-weevil.jurassic.ninja).

How I tested this was to first do a complete sync with 2.3.2, then upgrade. Detailed steps:

0. Optional: delete all products / items in Facebook so we have clean start state.
1. Deactivate and delete Facebook plugin on the site.
2. Install Facebook for WooCommerce 2.3.2 (current release) from WPORG.
3. Activate plugin.
4. Ensure debug logging is enabled - `Marketing > Facebook > Connection > Enable debug mode`. (So we can view logs to confirm sync.) Optionally delete logs here so less data to search/scroll.
5. Ensure plugin version option is < 2.3.3. Browse to `/wp-admin/options.php` (TIL!), set `wc_facebook_for_woocommerce_version` to 2.3.2.
6. Trigger a sync to ensure 2.3.2 product sync has completed at least once.
7. Upload Facebook for WooCommerce 2.3.3.dev-1 zip and replace / overwrite current plugin.

Then I checked `Commerce > Catalogue > Items` on Facebook, `WooCommerce > Status > Logs` on Woo. I checked over about 30 mins and didn't see a new sync request (`POST https://graph.facebook.com/v9.0/330833321685453/items_batch`), didn't see changes in Facebook products.

At that point I decided to force a manual sync via `Marketing > Facebook > Product sync > Sync products`. Then confirmed the sync had run and my large/medium variants were visible in catalogue.

**Comment by haszari** [comment]
FYI I also saw this error on the facebook end when looking at variants. Not sure exactly how to reproduce - @denniskwon let me know if you want more info about this or if I should log it somewhere.

Screen Shot 2021-03-19 at 2 16 06 PM

**Comment by budzanowski** [comment]
@haszari
I did the same test for updates and this is what I have seen in the logs:
```
03-19-2021 @ 13:16:34 - Starting upgrade to v2.3.3
03-19-2021 @ 13:16:34 - Upgrade to v2.3.3 complete
03-19-2021 @ 13:16:37 - Request
Request
method: POST
uri: https://graph.facebook.com/v9.0/5268981159841230/items_batch
user-agent: Facebook-for-WooCommerce/2.3.3-dev.1 (WooCommerce/5.1.0; WordPress/5.7)
```

So the process was starterd.

**Comment by haszari** [comment]
> I did the same test for updates and this is what I have seen in the logs

Thanks @budzanowski  - there must have been something quirky about my site setup. I had upgraded and downgraded facebook a few times, so I retested today on a completely clean site. 

After uploading the 2.3.3 zip and activating I saw a successful sync in the logs. Also, the variations showed up as Large/Small after the upgrade - great to see that enhancement:

Screen Shot 2021-03-22 at 10 07 32 AM

So that confirms it's working - there must have been some state blocking it in my other store (other than `wc_facebook_for_woocommerce_version` option). Would be good to clarify this but not a big deal, since most customers will only upgrade once, from 2.3.2 to 2.3.3 :)

**Pull request merged**
